<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Stateless;
use Neoan3\Frame\Cafe;
use Neoan3\Model\UserModel;
use Neoan3\Apps\DbException;

class Login extends Cafe
{
    /**
     * @param array $credentials
     *
     * @return array|mixed
     * @throws \Neoan3\Apps\DbException
     * @throws \Neoan3\Core\RouteException
     */
    function postLogin(array $credentials)
    {
        $user = UserModel::login($credentials);
        $jwt = Stateless::assign($user['id'],'user');
        return ['user'=>$user, 'token'=> $jwt];
    }

}
